import { BuildingBlock } from '@factordao/sdk-studio';
import { Token, Protocols } from '../types';

export const tokens: Token[] = [
  {
    address: '0x0000000000000000000000000000000000000000',
    name: 'Ethereum',
    symbol: 'ETH',
    decimals: 18,
    buildingBlocks: [BuildingBlock.DEPOSIT, BuildingBlock.WITHDRAW],
    protocols: [],
  },
  {
    address: '0x7cb16cb78ea464ad35c8a50abf95dff3c9e09d5d',
    name: '0xBitcoin',
    symbol: '0xBTC',
    decimals: 8,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xba5ddd1f9d7f570dc94a51479a000e3bce967196',
    name: 'Aave Token',
    symbol: Protocols.AAVE,
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.LEND,
      BuildingBlock.WITHDRAW,
      BuildingBlock.DEPOSIT,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [Protocols.AAVE, Protocols.UNISWAP],
  },
  {
    address: '0x8888888888f004100C0353d657BE6300587A6CcD',
    name: 'ACryptoS',
    symbol: 'ACS',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x09e18590e8f76b6cf471b3cd75fe1a1a9d2b2c2b',
    name: 'ArbDoge AI',
    symbol: 'AIDOGE',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x0e15258734300290a651fdbae8deb039a8e7a2fa',
    name: 'Token Alch',
    symbol: 'ALCH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x8fbd420956fdd301f4493500fd0bcaaa80f2389c',
    name: 'Amy Finance Token',
    symbol: 'AMY',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xaeaeed23478c3a4b798e4ed40d8b7f41366ae861',
    name: 'Ankr Network',
    symbol: 'ANKR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xe05a08226c49b636acf99c40da8dc6af83ce5bb3',
    name: 'Ankr Staked ETH',
    symbol: 'ankrETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x912ce59144191c1204e64559fe8253a0e49e6548',
    name: 'Arbitrum',
    symbol: 'ARB',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.LEND,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [
      Protocols.OPENOCEAN,
      Protocols.AAVE,
      Protocols.UNISWAP,
      Protocols.COMPOUND,
    ],
  },
  {
    address: '0xd5954c3084a1ccd70b4da011e67760b8e78aee84',
    name: 'Arbidex',
    symbol: 'ARX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xeb466342c4d449bc9f53a865d5cb90586f405215',
    name: 'Axelar USDC',
    symbol: 'axlUSDC',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xbfa641051ba0a0ad1b0acf549a89536a0d76472e',
    name: 'Badger',
    symbol: 'Badger',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x040d1edc9569d4bab2d15287dc5a4f10f56a56b8',
    name: 'Balancer',
    symbol: 'BAL',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x1A5B0aaF478bf1FDA7b934c76E7692D722982a6D',
    name: 'Buffer Token',
    symbol: 'BFR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x99c409e5f62e4bd2ac142f17cafb6810b8f0baae',
    name: 'Beefy.Finance',
    symbol: 'BIFI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x031d35296154279dc1984dcd93e392b1f946737b',
    name: 'Cap token',
    symbol: 'CAP',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xfa42da1bd08341537a44a4ca9d236d1c00a98b40',
    name: 'Carboncoin',
    symbol: 'CARBON',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3a8b787f78d775aecfeea15706d4221b40f345ab',
    name: 'Celer token',
    symbol: 'CELR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x15b2fb8f08e4ac1ce019eadae02ee92aedf06851',
    name: 'Chronos Finance',
    symbol: 'CHR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x354a6da3fcde098f8389cad84b0182725c6c91de',
    name: 'Compound',
    symbol: 'COMP',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xf4d48ce3ee1ac3651998971541badbb9a14d7234',
    name: 'Cream Finance',
    symbol: 'Cream',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x250Caff618cf205997309940c14C52B5DcEb351E',
    name: 'CrowdSwap',
    symbol: 'CROWD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x11cdb42b0eb46d95f990bedd4695a6e3fa034978',
    name: 'Curve Dao ',
    symbol: 'CRV',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xeb8E93A0c7504Bffd8A8fFa56CD754c63aAeBFe8',
    name: 'Overnight.fi DAI',
    symbol: 'DAI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1',
    name: 'Dai Stablecoin',
    symbol: 'DAI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.REPAY,
      BuildingBlock.BORROW,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP, Protocols.AAVE],
  },
  {
    address: '0xcAB86F6Fb6d1C2cBeeB97854A0C023446A075Fe3',
    name: 'deBridge Ether',
    symbol: 'deETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x1dDcaa4Ed761428ae348BEfC6718BCb12e63bFaa',
    name: 'deBridge USD Coin',
    symbol: 'deUSDC',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xae6aab43c4f3e0cea4ab83752c278f8debaba689',
    name: 'dForce',
    symbol: 'DF',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x69eb4fa4a2fbd498c257c57ea8b7655a2559a581',
    name: 'DODO bird',
    symbol: 'DODO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x4425742f1ec8d98779690b5a3a6276db85ddc01a',
    name: 'The Doge NFT',
    symbol: 'DOG',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x6c2c06790b3e3e3c38e12ee22f8183b37a13ee55',
    name: 'Dopex',
    symbol: 'DPX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xc3ae0333f0f34aa734d5493276223d95b8f9cb37',
    name: 'DXdao',
    symbol: 'DXD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
    name: 'ETH',
    symbol: 'ETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x6dd963c510c2d2f09d5eddb48ede45fed063eb36',
    name: 'Factor',
    symbol: 'FCTR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/FCTR.png',
  },
  {
    address: '0xb348b87b23d5977e2948e6f36ca07e1ec94d7328',
    name: 'SwapFish',
    symbol: 'FISH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x876ec6be52486eeec06bc06434f3e629d695c6ba',
    name: 'FluidFi',
    symbol: 'FLUID',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xcbe94d75ec713b7ead84f55620dc3174beeb1cfe',
    name: 'FORE Protocol',
    symbol: 'FORE',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xdb298285fe4c5410b05390ca80e8fbe9de1f259b',
    name: 'handle.fi',
    symbol: 'FOREX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x17fc002b466eec40dae837fc4be5c67993ddbd6f',
    name: 'Frax ',
    symbol: 'FRAX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x17fc002b466eec40dae837fc4be5c67993ddbd6f',
    name: 'Frax',
    symbol: 'FRAX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.BORROW,
      BuildingBlock.LEND,
      BuildingBlock.REPAY,
      BuildingBlock.WITHDRAW,
      BuildingBlock.DEPOSIT,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [Protocols.AAVE, Protocols.UNISWAP],
  },
  {
    address: '0x178412e79c25968a32e89b11f63b33f733770c2a',
    name: 'Frax Ether',
    symbol: 'FRXETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xbdef0e9ef12e689f366fe494a7a7d0dad25d9286',
    name: 'Fuse Token',
    symbol: 'FUSE',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x9d2F299715D94d8A7E6F5eaa8E654E8c74a988A7',
    name: 'Frax Share',
    symbol: 'FXS',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x872bad41cfc8ba731f811fea8b2d0b9fd6369585',
    name: 'BattleFly',
    symbol: 'gFLY',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x7dff72693f6a4149b17e7c6314655f6a9f7c8b33',
    name: 'GHO',
    symbol: 'GHO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a',
    name: 'GMX',
    symbol: 'GMX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP, Protocols.COMPOUND],
  },
  {
    address: '0xa0b862f60edef4452f25b4160f177db44deb6cf1',
    name: 'Gnosis Token',
    symbol: 'GNO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x18c11fd286c5ec11c3b683caa813b77f5163a122',
    name: 'Gains Network',
    symbol: 'GNS',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x07e49d5de43dda6162fa28d24d5935c151875283',
    name: 'CIV',
    symbol: 'GOVI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3d9907f9a368ad0a51be60f7da3b97cf940982d8',
    name: 'Camelot Token',
    symbol: 'GRAIL',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x23a941036ae778ac51ab04cea08ed6e2fe103614',
    name: 'Graph Token',
    symbol: 'GRT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x580e933d90091b9ce380740e3a4a39c67eb85b4c',
    name: 'GameSwift',
    symbol: 'GSWIFT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x431402e8b9de9aa016c743880e04e517074d8cec',
    name: 'Hegic',
    symbol: 'HEGIC',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x83d6c8c06ac276465e4c92e7ac8c23740f435140',
    name: 'HMX',
    symbol: 'HMX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x10010078a54396f62c96df8532dc2b4847d47ed3',
    name: 'Hundred Finance',
    symbol: 'HND',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x371c7ec6d8039ff7933a2aa28eb827ffe1f52f07',
    name: 'JOE',
    symbol: 'JOE',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x10393c20975cF177a3513071bC110f7962CD67da',
    name: 'Jones DAO',
    symbol: 'JONES',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3A18dcC9745eDcD1Ef33ecB93b0b6eBA5671e7Ca',
    name: 'Kujira',
    symbol: 'KUJI',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x04cb2d263a7489f02d813eaab9ba1bb8466347f2',
    name: 'QIAN governance token',
    symbol: 'KUN',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3b60ff35d3f7f62d636b067dd0dc0dfdad670e4e',
    name: 'Milady Meme Coin',
    symbol: 'LADYS',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3cd1833ce959e087d0ef0cb45ed06bffe60f23ba',
    name: 'Land',
    symbol: 'LAND',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x13ad51ed4f1b7e9dc168d8a00cb3f4ddd85efa60',
    name: 'Lido DAO',
    symbol: 'LDO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xf97f4df75117a78c1a5a0dbb814af92458539fb4',
    name: 'ChainLink Token',
    symbol: 'LINK',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP, Protocols.AAVE],
  },
  {
    address: '0x289ba1701c2f088cf0faf8b3705246331cb8a839',
    name: 'Livepeer',
    symbol: 'LPT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x46d0ce7de6247b0a95f67b43b589b4041bae7fbe',
    name: 'LoopringCoin V2',
    symbol: 'LRC',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x93b346b6bc2548da6a1e7d98e9a421b42541425b',
    name: 'LUSD Stablecoin',
    symbol: 'LUSD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.BORROW,
      BuildingBlock.LEND,
      BuildingBlock.REPAY,
      BuildingBlock.WITHDRAW,
      BuildingBlock.DEPOSIT,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [Protocols.AAVE, Protocols.UNISWAP],
  },
  {
    address: '0x079504b86d38119f859c4194765029f692b7b7aa',
    name: 'Lyra Finance',
    symbol: 'LYRA',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x539bde0d7dbd336b79148aa742883198bbf60342',
    name: 'MAGIC',
    symbol: 'MAGIC',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x99f40b01ba9c469193b360f72740e416b17ac332',
    name: 'MATH Token',
    symbol: 'MATH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x4e352cf164e64adcbad318c3a1e222e9eba4ce42',
    name: 'MCDEX Token',
    symbol: 'MCB',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xfea7a6a0b346362bf88a9e4a88416b77a57d6c2a',
    name: 'Magic Internet Money',
    symbol: 'MIM',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x2e9a6Df78E42a30712c10a9Dc4b1C8656f8F2879',
    name: 'Maker',
    symbol: 'MKR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x56b251d4b493ee3956e3f899d36b7290902d2326',
    name: 'MMFinance',
    symbol: 'MMF',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xA6D7D0e650aa40FFa42d845A354c12c2bc0aB15f',
    name: 'Mummy Finance',
    symbol: 'MMY',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x15a808ed3846d25e88ae868de79f1bcb1ac382b5',
    name: 'Metavault DAO',
    symbol: 'MVD',
    decimals: 9,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xed3fb761414da74b74f33e5c5a1f78104b188dfc',
    name: 'ArbiNYAN',
    symbol: 'NYAN',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xDCbf4CB83d27C408B30dD7F39bfcabD7176B1Ba3',
    name: 'OpenOcean',
    symbol: 'OOE',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xa3d1a8deb97b111454b294e2324efad13a9d8396',
    name: 'Overnight Finance',
    symbol: 'OVN',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x0c880f6761f1af8d9aa9c466984b80dab9a8c9e8',
    name: 'Pendle',
    symbol: Protocols.PENDLE,
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x965772e0e9c84b6f359c8597c891108dcf1c5b1a',
    name: 'Pickle Finance',
    symbol: 'PICKLE',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x51fc0f6660482ea73330e414efd7808811a57fa2',
    name: 'premia',
    symbol: 'PREMIA',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x17a8541b82bf67e10b0874284b4ae66858cb1fd5',
    name: 'Possum Labs',
    symbol: 'PSM',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x07aaa29e63ffeb2ebf59b33ee61437e1a91a3bb2',
    name: ' QIAN second generation dollar',
    symbol: 'QSD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418',
    name: 'Ramses Exchange',
    symbol: 'RAM',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3082CC23568eA640225c2467653dB90e9250AaA0',
    name: 'Radiant V2 Token',
    symbol: 'RDNT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x033f193b3fceb22a440e89a2867e8fee181594d9',
    name: 'Rodeo Finance',
    symbol: 'RDO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x32eb7902d4134bf98a28b963d26de779af92a212',
    name: 'Dopex Rebate Token',
    symbol: 'RDPX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xDBf31dF14B66535aF65AaC99C32e9eA844e14501',
    name: 'renBTC',
    symbol: 'RENBTC',
    decimals: 8,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xec70dcb4a1efa46b8f2d97c310c9c4790ba5ffa8',
    name: 'Rocket Pool ETH',
    symbol: 'rETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.BORROW,
      BuildingBlock.LEND,
      BuildingBlock.REPAY,
      BuildingBlock.WITHDRAW,
      BuildingBlock.DEPOSIT,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [Protocols.AAVE, Protocols.UNISWAP],
  },
  {
    address: '0xef888bca6ab6b1d26dbec977c455388ecd794794',
    name: 'Rari Governance Token',
    symbol: 'RGT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xd6c0156E85deCdF2983c7A2c4A3015eD268d6f8A',
    name: 'Roseon',
    symbol: 'ROSX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xabd587f2607542723b17f14d00d99b987c29b074',
    name: 'SmarDex',
    symbol: 'SDEX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x7ba4a00d54a07461d9db2aef539e91409943adc9',
    name: 'Stake DAO Token',
    symbol: 'SDT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x95ab45875cffdba1e5f451b950bc2e42c0053f39',
    name: 'Staked Frax Ether',
    symbol: 'SFRXETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x9E758B8a98a42d612b3D38B66a22074DC03D7370',
    name: 'Symbiosis Finance',
    symbol: 'SIS',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x463913d3a3d3d291667d53b8325c598eb88d3b0e',
    name: 'SolidLizard',
    symbol: 'SLIZ',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3647c54c4c2c65bc7a2d63c0da2809b399dbbdc0',
    name: 'Solv Protocol',
    symbol: 'SolvBTC',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x346c574c56e1a4aaa8dc88cda8f7eb12b39947ab',
    name: 'SolvBTC Babylon',
    symbol: 'SolvBTC.BBN',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xafafd68afe3fe65d376eec9eab1802616cfaccb8',
    name: 'SolvBTC Ethena',
    symbol: 'SolvBTC.ENA',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x11f98c7e42a367dab4f200d2fdc460fb445ce9a8',
    name: 'SpartaDEX',
    symbol: 'SPARTA',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3e6648c5a70a150a88bce65f4ad4d506fe15d2af',
    name: 'Spell Token',
    symbol: 'SPELL',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x6694340fc020c5E6B96567843da2df01b2CE1eb6',
    name: 'Stargate Finance',
    symbol: 'STG',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x5db7b150c5f38c5f5db11dcbdb885028fcc51d68',
    name: 'Sterling Finance',
    symbol: 'STR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xa970af1a584579b618be4d69ad6f73459d112f95',
    name: 'Synth sUSD',
    symbol: 'SUSD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xd4d42f0b6def4ce0383636770ef773390d85c61a',
    name: 'SushiToken',
    symbol: 'SUSHI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xde903e2712288a1da82942dddf2c20529565ac30',
    name: 'Swapr',
    symbol: 'SWPR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xfac38532829fdd744373fdcd4708ab90fa0c4078',
    name: 'tLPT',
    symbol: 'TLPT',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x982239D38Af50B0168dA33346d85Fb12929c4c07',
    name: 'Arbitrove Protocol',
    symbol: 'TROVE',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07',
    name: 'TrueUSD',
    symbol: 'TUSD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3',
    name: 'Umami',
    symbol: 'UMAMI',
    decimals: 9,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0',
    name: 'Uniswap',
    symbol: 'UNI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xe80772Eaf6e2E18B651F160Bc9158b2A5caFCA65',
    name: 'Overnight.fi USD+',
    symbol: 'USD+',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xaf88d065e77c8cc2239327c5edb3a432268e5831',
    name: 'USD Coin',
    symbol: 'USDC',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [
      Protocols.OPENOCEAN,
      Protocols.UNISWAP,
      Protocols.AAVE,
      Protocols.COMPOUND,
    ],
  },
  {
    address: '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8',
    name: 'USD Coin (Arb1)',
    symbol: 'USDC.e',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [
      Protocols.OPENOCEAN,
      Protocols.UNISWAP,
      Protocols.AAVE,
      Protocols.COMPOUND,
    ],
  },
  {
    address: '0x680447595e8b7b3aa1b43beb9f6098c79ac2ab3f',
    name: 'USDD',
    symbol: 'USDD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x59d9356e565ab3a36dd77763fc0d87feaf85508c',
    name: 'Mountain Protocol USDM',
    symbol: 'USDM',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9',
    name: 'Tether USD',
    symbol: 'USDT',
    decimals: 6,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP, Protocols.AAVE],
  },
  {
    address: '0x641441c631e2f909700d2f41fd87f0aa6a6b4edb',
    name: 'dForce USD',
    symbol: 'USX',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x088cd8f5ef3652623c22d48b1605dcfe860cd704',
    name: 'Vela Token',
    symbol: 'VELA',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x995c235521820f2637303ca1970c7c044583df44',
    name: 'VISOR',
    symbol: 'VISR',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x64343594ab9b56e99087bfa6f2335db24c2d1f17',
    name: 'Vesta Stable',
    symbol: 'VST',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xa684cd057951541187f288294a1e1C2646aA2d24',
    name: 'Vesta Finance ',
    symbol: 'VSTA',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f',
    name: 'Wrapped BTC',
    symbol: 'WBTC',
    decimals: 8,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [
      Protocols.OPENOCEAN,
      Protocols.UNISWAP,
      Protocols.AAVE,
      Protocols.COMPOUND,
    ],
  },
  {
    address: '0x35751007a407ca6feffe80b3cb397736d2cf4dbe',
    name: 'Wrapped eETH',
    symbol: 'WEETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP, Protocols.AAVE],
  },
  {
    address: '0x82af49447d8a07e3bd95bd0d56f35241523fbab1',
    name: 'Wrapped Ether',
    symbol: 'WETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.LEND,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    protocols: [
      Protocols.AAVE,
      Protocols.OPENOCEAN,
      Protocols.UNISWAP,
      Protocols.COMPOUND,
    ],
  },
  {
    address: '0x7b5eb3940021ec0e8e463d5dbb4b7b09a89ddf96',
    name: 'Wombat Exchange',
    symbol: 'WOM',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xcafcd85d8ca7ad1e1c6f82f651fa15e33aefd07b',
    name: 'Wootrade Network',
    symbol: 'WOO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x5979d7b546e38e414f7e9822514be443a4800529',
    name: 'Wrapped stETH',
    symbol: 'WSTETH',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.LEND,
      BuildingBlock.BORROW,
      BuildingBlock.REPAY,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP, Protocols.AAVE],
  },
  {
    address: '0x4cb9a7ae498cedcbb5eae9f25736ae7d428c9d66',
    name: 'XAI',
    symbol: 'XAI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x9ef758ac000a354479e538b8b2f01b917b8e89e7',
    name: 'xDollar',
    symbol: 'XDO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x00cbcf7b3d37844e44b888bc747bdd75fcf4e555',
    name: 'xPet.tech',
    symbol: 'XPET',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3509f19581afedeff07c53592bc0ca84e4855475',
    name: 'xDollar Stablecoin',
    symbol: 'XUSD',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x82e3a8f066a6989666b031d916c43672085b1582',
    name: 'yearn.finance',
    symbol: 'YFI',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0xdb96f8efd6865644993505318cc08ff9c42fb9ac',
    name: 'ZeroTwOhm',
    symbol: 'Z2O',
    decimals: 9,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x6985884C4392D348587B19cb9eAAf157F13271cd',
    name: 'LayerZero',
    symbol: 'ZRO',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
  {
    address: '0x3b475f6f2f41853706afc9fa6a6b8c5df1a2724c',
    name: 'Zyberswap',
    symbol: 'ZYB',
    decimals: 18,
    buildingBlocks: [
      BuildingBlock.SWAP,
      BuildingBlock.DEPOSIT,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
      BuildingBlock.WITHDRAW,
    ],
    protocols: [Protocols.OPENOCEAN, Protocols.UNISWAP],
  },
];
