import { Token, Protocols, BuildingBlock } from '../../types';

export const tokens: Token[] = [
  {
    address: '0x0000000000000000000000000000000000000000',
    symbol: 'S',
    name: 'S',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/S.png',
  },
  {
    address: '0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38',
    symbol: 'wS',
    name: 'Wrapped Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/WS.png',
  },
  {
    address: '0x29219dd400f2Bf60E5a23d13Be72B486D4038894',
    symbol: 'USDC.e',
    name: 'Bridged USDC (Sonic Labs)',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/USDC.E.png',
  },
  {
    address: '0x6047828dc181963ba44974801FF68e538dA5eaF9',
    symbol: 'USDT',
    name: 'USDT',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/USDT.png',
  },
  {
    address: '0x50c42dEAcD8Fc9773493ED674b675bE577f2634b',
    symbol: 'WETH',
    name: 'WETH',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/WETH.png',
  },
  {
    address: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
    symbol: 'WBTC',
    name: 'WBTC',
    decimals: 8,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/WBTC.png',
  },
  {
    address: '0xddF26B42C1d903De8962d3F79a74a501420d5F19',
    symbol: 'EQUAL',
    name: 'Equalizer on Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/EQUAL.png',
  },
  {
    address: '0x3333b97138D4b086720b5aE8A7844b1345a33333',
    symbol: 'SHADOW',
    name: 'Shadow',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SHADOW.png',
  },
  {
    address: '0x2D0E0814E62D80056181F5cd932274405966e4f0',
    symbol: 'BEETS',
    name: 'Beets',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/BEETS.png',
  },
  {
    address: '0xd3DCe716f3eF535C5Ff8d041c1A41C3bd89b97aE',
    symbol: 'scUSD',
    name: 'Sonic USD',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SCUSD.png',
  },
  {
    address: '0xE5DA20F15420aD15DE0fa650600aFc998bbE3955',
    symbol: 'stS',
    name: 'Beets Staked Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/STS.png',
  },
  {
    address: '0x43eDD7f3831b08FE70B7555ddD373C8bF65a9050',
    symbol: 'frxETH',
    name: 'Frax Ether',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/FRXETH.png',
  },
  {
    address: '0xb1e25689D55734FD3ffFc939c4C3Eb52DFf8A794',
    symbol: 'OS',
    name: 'Origin Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/OS.png',
  },
  {
    address: '0x005851f943ee2957B1748957F26319e4f9EdeBC1',
    symbol: '$AG',
    name: 'Silver',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/$AG.png',
  },
  {
    address: '0x05e31a691405d06708A355C029599c12d5da8b28',
    symbol: 'fSONIC',
    name: 'FantomSonicInu',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/FSONIC.png',
  },
  {
    address: '0x0e0Ce4D450c705F8a0B6Dd9d5123e3df2787D16B',
    symbol: 'WAGMI',
    name: 'Wagmi',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/WAGMI.png',
  },
  {
    address: '0x131F5AE1CBfEFe8EFbDf93dA23fa4d39F14a817c',
    symbol: 'FROQ',
    name: 'Froq',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/FROQ.png',
  },
  {
    address: '0x17Af1Df44444AB9091622e4Aa66dB5BB34E51aD5',
    symbol: 'THC',
    name: 'Tin Hat Cat',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/THC.png',
  },
  {
    address: '0x3333111A391cC08fa51353E9195526A70b333333',
    symbol: 'x33',
    name: 'Shadow Liquid Staking Token',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/X33.png',
  },
  {
    address: '0x3a516e01f82c1e18916ED69a81Dd498eF64bB157',
    symbol: 'SNAKE',
    name: 'SNAKE',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SNAKE.png',
  },
  {
    address: '0x3bcE5CB273F0F148010BbEa2470e7b5df84C7812',
    symbol: 'scETH',
    name: 'Sonic ETH',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SCETH.png',
  },
  {
    address: '0x4EEC869d847A6d13b0F6D1733C5DEC0d1E741B4f',
    symbol: 'INDI',
    name: 'Indi',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/INDI.png',
  },
  {
    address: '0x53e24706D6642CA495498557415b1af7A025D8Da',
    symbol: 'USD+',
    name: 'USD+',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0x6BA47940f738175d3F8C22Aa8EE8606eaAe45eb2',
    symbol: 'sS',
    name: 'SupraFi Staked Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SS.png',
  },
  {
    address: '0x6fB9897896Fe5D05025Eb43306675727887D0B7c',
    symbol: 'HEDGY',
    name: 'HEDGY the hedgehog',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/HEDGY.png',
  },
  {
    address: '0x71E99522EaD5E21CF57F1f542Dc4ad2E841F7321',
    symbol: 'METRO',
    name: 'Metropolis Token',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/METRO.png',
  },
  {
    address: '0x777CF5ba9C291A1A8f57FF14836F6F9dC5c0F9Dd',
    symbol: 'SOLID',
    name: 'Solidly',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SOLID.png',
  },
  {
    address: '0x79bbF4508B1391af3A0F4B30bb5FC4aa9ab0E07C',
    symbol: 'Anon',
    name: 'HeyAnon',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/ANON.png',
  },
  {
    address: '0x7A08Bf5304094CA4C7b4132Ef62b5EDc4a3478B7',
    symbol: 'ECO',
    name: 'SonicEco',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/ECO.png',
  },
  {
    address: '0x7A0C53F7eb34C5BC8B01691723669adA9D6CB384',
    symbol: 'BOO',
    name: 'SpookyToken V2',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/BOO.png',
  },
  {
    address: '0x7B0a41f0c17474e41a0c36c0Bf33b9AED06eE9f5',
    symbol: 'SNS',
    name: 'Sonic Name Service',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SNS.png',
  },
  {
    address: '0x80Eede496655FB9047dd39d9f418d5483ED600df',
    symbol: 'frxUSD',
    name: 'Frax USD',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/FRXUSD.png',
  },
  {
    address: '0x9F0dF7799f6FDAd409300080cfF680f5A23df4b1',
    symbol: 'wOS',
    name: 'Wrapped Origin Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/WOS.png',
  },
  {
    address: '0x9fDbC3f8Abc05Fa8f3Ad3C17D2F806c1230c4564',
    symbol: 'GOGLZ',
    name: 'GOGGLES',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/GOGLZ.png',
  },
  {
    address: '0xA04BC7140c26fc9BB1F36B1A604C7A5a88fb0E70',
    symbol: 'SWPx',
    name: 'SwapX',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/SWPX.png',
  },
  {
    address: '0xb0695ce12c56AAe40894235e2d1888D0b62Dd110',
    symbol: 'FIVE',
    name: 'DeFive',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/FIVE.png',
  },
  {
    address: '0xC96dE26018A54D51c097160568752c4E3BD6C364',
    symbol: 'FBTC',
    name: 'Fire Bitcoin',
    decimals: 8,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/FBTC.png',
  },
  {
    address: '0xE51EE9868C1f0d6cd968A8B8C8376Dc2991BFE44',
    symbol: 'BRUSH',
    name: 'PaintSwap',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/BRUSH.png',
  },
  {
    address: '0xe6cc4D855B4fD4A9D02F46B9adae4C5EfB1764B5',
    symbol: 'LUDWIG',
    name: 'LUDWIG',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/LUDWIG.png',
  },
  {
    address: '0xe715cbA7B5cCb33790ceBFF1436809d36cb17E57',
    symbol: 'EURC.e',
    name: 'Bridged EURC (Sonic Labs)',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/EURC.E.png',
  },
  {
    address: '0xBb30e76d9Bb2CC9631F7fC5Eb8e87B5Aff32bFbd',
    symbol: 'scBTC',
    name: 'Sonic BTC',
    decimals: 8,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0x578Ee1ca3a8E1b54554Da1Bf7C583506C4CD11c6',
    symbol: 'aSonUSDC',
    name: 'Aave Sonic USDC',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0x6C5E14A212c1C3e4Baf6f871ac9B1a969918c131',
    symbol: 'aSonwS',
    name: 'Aave Sonic wS',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0xe18Ab82c81E7Eecff32B8A82B1b7d2d23F1EcE96',
    symbol: 'aSonWETH',
    name: 'Aave Sonic WETH',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0x18B7B8695165290f2767BC63c36D3dFEa4C0F9bB',
    symbol: 'waSonwS',
    name: 'Wrapped Aave Sonic wS',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0x6646248971427B80ce531bdD793e2Eb859347E55',
    symbol: 'waSonUSDC',
    name: 'Wrapped Aave Sonic USDC',
    decimals: 6,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0xeB5e9B0ae5bb60274786C747A1A2A798c11271E0',
    symbol: 'waSonWETH',
    name: 'Wrapped Aave Sonic WETH',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0xC5cB0B67D24d72b9D86059344c88Fb3cE93BF37C',
    symbol: '9MM',
    name: '9MM',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/9MM.png',
  },
  {
    address: '0x871A101Dcf22fE4fE37be7B654098c801CBA1c88',
    symbol: 'beS',
    name: 'Beefy Sonic',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
  {
    address: '0x2dDCF85D3Cf27DEA338e0371D38409Ba80058630',
    symbol: 'wSLT',
    name: 'BMX: Wrapped Sonic Liquidity Token',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
    logoUrl:
      'https://raw.githubusercontent.com/FactorDAO/factor-tokenlist/main/assets/sonic/WSLT.png',
  },
  {
    address: '0x9E462d5603Bb983b74e941Ebd5CE9Ea76f3a9e1e',
    symbol: 'SLT',
    name: 'BMX: Sonic Liquidity Token',
    decimals: 18,
    protocols: [Protocols.UNISWAP, Protocols.OPENOCEAN],
    buildingBlocks: [
      BuildingBlock.DEPOSIT,
      BuildingBlock.WITHDRAW,
      BuildingBlock.SWAP,
      BuildingBlock.CREATE_LP,
      BuildingBlock.PROVIDE_LIQUIDITY,
    ],
  },
];
